namespace: langfuse

helmGlobals:
  chartHome: "charts"

helmCharts:
  - name: "postgresql"
    releaseName: "db"
    version: "15.4.2"
    repo: "https://charts.bitnami.com/bitnami"
    valuesFile: "./charts/postgresql-values.yaml"
  # - name: "langfuse"
  #   releaseName: "langfuse"
  #   version: "0.2.1"
  #   repo: "https://langfuse.github.io/langfuse-k8s"
  #   valuesFile: "./charts/langfuse-values.yaml"

resources:
  - "./resources/namespace.yaml"
  - "./resources/service.yaml"
  - "./resources/deployment.yaml"

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: langfuse-config
    envs:
    - "./files/.env.config.secret"

configMapGenerator:
  - name: langfuse-config
    envs:
      - "./files/.env.config.configmap"
