apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlflow

helmCharts:
- name: mlflow
  includeCRDs: false
  releaseName: mlflow
  version: 0.11.1
  repo: https://charts.bitnami.com/bitnami
  valuesFile: values.yaml

resources:
- namespace.yaml