apiVersion: batch/v1
kind: Job
metadata:
  name: sync-files
spec:
  template:
    spec:
      containers:
      - name: sync
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "minio"
        - name: AWS_SECRET_ACCESS_KEY
          value: "minio123"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        image: docker.io/amazon/aws-cli:latest
        # command: ["/bin/sh"]
        args:
          - "s3"
          - "sync"
          - "/local-storage"
          - "s3://backup"
          - "--endpoint-url=http://minio.minio.svc.cluster.local:9000"
          - "--no-verify-ssl"
        volumeMounts:
        - name: local-storage 
          mountPath: /local-storage
      volumes:
      - name: local-storage 
        persistentVolumeClaim:
          claimName: local-storage
      restartPolicy: Never
  backoffLimit: 3